[versions]
decompose = "1.0.0-alpha-04"
agp = "7.2.2"
kotlin = "1.7.10"
serialization = "1.3.3"
coroutines = "1.6.4"
koin = "3.2.0"
reaktive = "1.2.2"
mviKotlin = "3.0.1"
ktor = "2.0.3"
compose = "1.3.0-alpha03"
composeCompiler = "1.3.0"
navigation = "2.5.1"
activity = "1.6.0-beta01"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

decompose-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extension-compose = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }

mviKotlin-mviKotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mviKotlin" }
mviKotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mviKotlin" }
mviKotlin-extensionCoroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mviKotlin" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okHttp = { module = "io.ktor:ktor-client-okhttp", version.ref= "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor"}
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose"}
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose"}
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

[bundles]

ktor = [
    "ktor-core",
    "ktor-serialization",
    "ktor-negotiation"
]

decompose = [
    "decompose-decompose",
    "decompose-extension-compose"
]

mviKotlin = [
    "mviKotlin-mviKotlin",
    "mviKotlin-main",
    "mviKotlin-extensionCoroutines"
]

compose = [
    "compose-foundation",
    "compose-material",
    "compose-navigation"
]