[versions]
agp = "7.2.2"
kotlin = "1.7.20"
serialization = "1.3.3"
coroutines = "1.6.4"
compose = "1.3.0-rc01"
composeCompiler = "1.3.2"
navigation = "2.5.1"
activity = "1.6.0-beta01"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose"}
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose"}
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

[bundles]

compose = [
    "compose-foundation",
    "compose-material",
    "compose-navigation"
]